# Generated by Django 4.0.3 on 2023-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
