# Generated by Django 4.0.3 on 2023-04-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_blog_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='bimage',
        ),
    ]
