# Generated by Django 4.0.3 on 2023-04-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_image_blog_bimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobileno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
